---
title: "Isotope Tracking  - Species based"
header-includes: \usepackage{mathtools} \usepackage{natbib}
output:
  pdf_document:
    citation_package: natbib
    keep_tex: yes
  word_document: default
bibliography: LargeFiles/library.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Note: For word, replace string:
# ${[...comment..]:$.$ <- $.$}  # ignore dots.
# [comment]:$$
```

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(.packages(), 'knitr', 'rmarkdown'), 'packages.bib' )
```


To obtain the masses of heavy $M^h$ and light isotopes $M^l$, the isotope signature $\delta ^{13}C$ is used where:

$$
\delta ^{13}C [‰] = \Big(\frac{R_{smp} - R_{std}}{R_{std}}\Big)\cdot 1000
$$


$$
R_{smp} = \frac{M^h}{M^l} 
$$

$$
R_{std} = 11237.2 \cdot 10^{-6}
$$


and where the total mass $M_{tot} = M^h + M^l$, we obtain:

$$
R_{std}\Big(\delta ^{13}C/1000+1 \Big)= \frac{M_{tot}-M^l}{M^l}
$$

$$
M^l = \frac{M_{tot}}{1+R_{std}(\delta ^{13}C/1000+1)}
$$


$$
M^h = M_{tot} - M^l 
$$



### Volatilization


Based on the porespace concentration, the mass flux escaping into the atmosphere is obtained as:

```{python}

def getVolatileMass(model, temp_air, theta_sat, mass, frac,
                    rel_diff_model="option-1", sorption_model="linear",
                    gas=True, isotopes=True,):
    # Volatilize only during peak volatilization time i.e., first 24 hrs, @Prueger2005.
    theta_layer = model.theta_z0
    theta_gas = max(theta_sat - theta_layer, scalar(0))
    # Convert to m (needed for final mass computation on cell basis)
    depth_m = model.z0 * 1 / 10 ** 3
    # Air boundary layer, assumed as 2m high
    thickness_a = scalar(2.0)  # m
    # Diffusion coefficient in air (cm^2/s); https://www.gsi-net.com
    #  D_ar (metolachlor) = 0.03609052694,  at reference Temp., in Kelvin, D_a,r)
    diff_ar = 0.03609 * 86400 * 1 / 10 ** 4  # m2/d
    # Diffusion coefficient adjusted to air Temp. in Kelvin, D_a
    diff_a = ((temp_air + 273.15) / 293.15) ** 1.75 * diff_ar  # m2/d

    if rel_diff_model == "option-1":
        # Millington and Quirk, 1960 (in Leistra, 2001, p.48)
        # a,b parameters: Jin and Jury, 1996 (in Leistra, 2001)
        diff_relative_gas = (diff_a * theta_gas ** 2 /
                             theta_sat ** (2 / 3))  # m2/d
    elif rel_diff_model == "option-2":
        # Currie 1960 (in Leistra, 2001)
        # a,b parameters: Baker, 1987 (in Leistra, 2001)
        diff_relative_gas = diff_a * 2.5 * theta_gas ** 3  # m2/d
    else:
        print("No appropriate relative diffusion parameter chosen")
        diff_relative_gas = diff_a  # m2/d
    # Transport resistance through air (r_a) and soil (r_s) layer
    r_a = thickness_a / diff_a  # d/m
    r_s = (0.5 * depth_m) / diff_relative_gas  # d/m

    conc_aq = getConcAq(model, 0, theta_sat, mass,
                        sorption_model=sorption_model, gas=gas, isotopes=isotopes)
    # Convert ug/L to ug/m3, as will be multiplying by cell's area in m2
    conc_aq *= 10**3  # ug/L * 10^3 L/m3
    volat_flux = (conc_aq / (r_a + r_s)) * cellarea()  # ug/day
    
    return volat_flux
            
```


# Runoff Mass

## K-film

```{python}

def getKfilm(model, runoffvelocity):
    """
    Note: Model uses run-off (mm) per day (i.e. timestep) as runoff velocity.
    Chemical parameter source:
    http://www.gsi-net.com/en/publications/gsi-chemical-database/single/377.html
    """
    # Dynamic viscosity of water (\mu) @25 Celsius = 8.9e-04 [Pa s]
    #   1 Pa = 1 N/(m s^2) = 1 Kg/(m s^2)
    #   Convert to g/(cm s): dyn_visc = 8.9e-03 [g/cm s]
    dyn_visc = 8.9e-03  # [g/cm s] @25 degrees, [@Shi2011]:\mu

    # Solute diffusivity in water (D_w)
    # Metolachlor = 5.0967719112e-006 (cm2 / s)
    diff_solute = 5.0967719112e-006  # [cm2 / s], [@Shi2011]:D_w
    Sc = dyn_visc / (model.p_b * diff_solute)  # (-) Schmidt number, [@Shi2011]:S_c

    # Reynolds number (dimensionless), 86400s = 1 day
    cell_length = 2 * 10 ** 3  # mm [@Shi2011]:L
    re = (model.p_b * 1 / 10 ** 2 * runoffvelocity * cell_length) / (dyn_visc * 86400)  # [-]  [@Shi2011]:Re
    kl = 0.664 * ((diff_solute * 86400 * 10 ** 2) / cell_length) * re ** (float(1) / 2) * Sc ** (float(1) / 3)  # mm/day
    return kl  # mm/day
    # NOT USED:
    # Kinematic water viscosity at 20 deg. Celsius = 1.004 x 10-6 (m2/s)
    # kin_visc = 1.004e-6 * 86400 * 10**6  # mm2/day
    
```

# Mass transfer to overland flow



```{python}


def getRunOffMass(model, theta_sat, precip, runoff_mm,
                  transfer_model="simple-mt", sorption_model="linear",
                  gas=True):
    depth, theta_layer, delta_layer = model.z0, model.theta_z0, model.delta_z0

    if sorption_model == "linear":
        # Retardation factor
        retard_layer = 1 + (model.p_b * model.k_d) / theta_layer
    else:
        retard_layer = 1

    # Aqueous concentration calculation
    if gas:
        # Leistra et al., 2001
        theta_gas = theta_sat - model.theta_z0
        # TODO: Check that all theta_gas >= 0
        conc_layer_aq = model.pestmass_z0 / ((cellarea() * depth) *
                                             (theta_gas * model.k_h + theta_layer * retard_layer))  # mg/L
    else:
        # Whelan, 1987 # No gas phase considered
        conc_layer_aq = (model.pestmass_z0 / cellarea()) / (theta_layer * retard_layer * depth)  # mg/L

    if transfer_model == "simple-mt":
        mass_ro = conc_layer_aq * runoff_mm * cellarea()  # mg
        deltaMass_ro = mass_ro * delta_layer
    elif transfer_model == "nu-mlm-ro":
        # non-uniform-mixing-layer-model-runoff (nu-mlm-ro)
        # Considers a decrease in effective transfer as mixing layer depth increases
        # Adapted from Ahuja and Lehman, 1983 in @Shi2011,
        # Adaptation replaces Precip by Runoff amount.
        b = 1  # [mm] Calibration constant, 1 >= b > 0 (b-ranges appear reasonable).
        # As b decreases, mass transfer increases, model.z0 in mm
        mass_ro = (runoff_mm * cellarea()) * exp(-b * model.z0) * conc_layer_aq  # mg
        deltaMass_ro = mass_ro * delta_layer
    elif transfer_model == "nu-mlm":
        # non-uniform-mixing-layer-model (nu-mlm)
        # Original from Ahuja and Lehman, 1983 in @Shi2011
        b = 1  # [mm] Calibration constant, 1 >= b > 0 (b-ranges appear reasonable).
        # As b decreases, mass transfer increases, model.z0 in mm
        mass_ro = (precip * cellarea()) * exp(-b * model.z0) * conc_layer_aq  # mg
        deltaMass_ro = mass_ro * delta_layer
    elif transfer_model == "d-mlm":
        # distributed mixing-layer-model (d-mlm)
        # Adapted from Havis et al., 1992, and
        # taking the K_L definition for laminar flow from Bennett and Myers, 1982.
        mass_ro = getKfilm(model, runoff_mm) * cellarea() * conc_layer_aq  # mg
        deltaMass_ro = mass_ro * delta_layer
    else:
        print("Run-off transfer model not stated")
        return None
        
    return {"mass_runoff": mass_ro, "deltaMass_runoff": deltaMass_ro}
    

```

