---
title: "BEACH Formalisms (S&B)"
date: "March 2, 2016"
output: pdf_document
bibliography: biblio.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Pesticide Fate and Mass Transfer

### Sorption

Sorption is described by a two-site model, composed of a Freundlich equilibrium component and a long-term kinetic component. Two-site models provide a reasonable compromise between detailed modelling of non-equilibirum sorption processes and experimental effort required to constrain model parameters [@TerHorst2013]. The two-site model is described by [@Leistra2001] where the concentration in liquid phase $C_L$ (mg m$^{-3}$) is:  

$$ 
C_{L(t,i,k)} = \frac{M_{p(t,i,k)} - M_{s(i,k)}(X_{eq(t,i,k)} + X_{ne(t,i,k)})}{A_i \cdot D_k \cdot \theta_{(t,i,k)}} \stepcounter{equation}\tag{\theequation}\label{totalConc} 
$$

where the pesticide mass $M_p$ (mg) is assumed to be perfectly mixed within the soil profile water content $\theta$ (-) of a soil layer $k$ with depth $D$ (m) and area $A_i$ (m$^{2}$). $X_{eq}$ and $X_{ne}$ are respectively, the pesticide masses sorbed in the equilibrium and non-equilibrium phases divided by the mass of dry soil (mg pesticide Kg$^{-1}$ soil). $M_s$ (Kg) is the mass of dry soil with bulk density $\rho_b$ (Kg m$^{-3}$) such that:

$$ M_{s(i,k)} = (1-\theta_{sat})\cdot D_k \cdot \rho_b \stepcounter{equation}\tag{\theequation}\label{massDrySoil} $$

The pesticide fraction in the equilibrium-sorbed phase $X_{eq}$ (mg Kg$^{-1}_{soil}$) is given by the Freundlich equation:

$$ X_{eq(t,i,k)} = K_{F,eq} \cdot C_{L,ref} \Big[\frac{C_{L(t,i,k)}}{C_{L,ref}}\Big]^{N} \stepcounter{equation}\tag{\theequation}\label{FreundEq} $$

where $K_{F,eq}$ (m$^{3}$ Kg$^{-1}$) is the equilibrium Freundlich coefficient, $C_{L,ref}$ (mg m$^{-3}$) is the reference concentration in liquid phase and N is the Freundlich exponent (-).\footnote{The adoption of a reference concentration $C_{L,ref}$ introduces the "advantage that the Freundlich coefficient has a regular unit, independent of the value of the exponent $N$ (i.e. typically between 0.7 and 1.1). $C_{L,ref}$ is set to $1.0 \times 10^{-3}$ (kg m$^{-3}$). This value should be within and checked against the range of concentrations in the measurements on which the Freundlich sorption coefficient were based." See Leistra et al., 2001, p.40.} 

Acccording to equation \eqref{FreundEq} the sorbed fraction at equilibrium is dependent on the liquid phase concentration. This requires solving for $C_{L}~via$ an iterative procedure using the following form of the Freundlich equation (Step 1):

$$ \frac{X_{eq}}{C_L}(i,k) = K_{F,eq} C_{L,ref}^{(1-N)} C_{L(i,k)}^{(N-1)} \stepcounter{equation}\tag{\theequation}\label{iterStep1} $$

To solve the right side of equation \eqref{iterStep1}, the initial iteration approximation value for $C_L$ is taken to be a linear partitioning such that:

$$ C_{L(i,k)} = \frac{M_{p(t,i,k)}}{D_k \cdot (\theta_{g(t,i,k)}K_H+\theta_{(t,i,k)}+\rho_bK_d)} \stepcounter{equation}\tag{\theequation}\label{linearEqConc} $$

where $M_p$ is the contaminant mass per surface area mixing in a soil profile of depth $D_k$, with gas phase pore volume fraction $\theta_{g}$, soil moisture content $\theta$, soil bulk density $\rho_b$ and with a linear sorption coefficient $K_d$. 

The resulting ratio on the left side of equation \eqref{iterStep1} will then be used in the equation for the partitioning of the compound over the soil phases in the soil volume:

$$ \frac{M_p}{D_k}(i,k) = \theta_{g(t,i,k)} C_{g(i,k)} + \theta_{(t,i,k)} C_{L(i,k)} + \rho_b X_{eq(i,k)} \stepcounter{equation}\tag{\theequation}\label{partitioning} $$

where $C_g$ is concentration in the gas phase [(check: (kg m$^{-3}$)]. Expressing equation \eqref{partitioning} in terms of $C_L$ yields: 

$$ \frac{M_p}{D_k}(i,k) = \theta_{g(t,i,k)} K_H C_{L(i,k)} + \theta_{(t,i,k)} C_{L(i,k)} + \rho_b \frac{X_{eq}}{C_L}(i,k) C_{L(i,k)} \stepcounter{equation}\tag{\theequation}\label{partitioning2} $$

rearranging and solving the right side of equation (Step 2):

$$ C_{L(i,k)} = \frac{M_{p(i,k)}}{D_k\cdot (\theta_{g(t,i,k)}K_H+\theta_{(t,i,k)}+\rho_b \frac{X_{eq}}{C_L}(i,k))} \stepcounter{equation}\tag{\theequation}\label{iterStep2} $$

The new value for $C_{L(i,k)}$ is introduced into the right hand side of equation \eqref{iterStep1} to continue the iteration until $\Delta C_L$ between Step 1 and Step 2 becomes very small (e.g. 10$^{-4}$).  

The final solution is then $C_{L(t,i,k)}$ and used to calculate $C_{g(t,i,k)}$ such that:

$$ C_{g(t,i,k)} = C_{L(t,i,k)} K_H \stepcounter{equation}\tag{\theequation}\label{gasConc}$$ 

Using equations \eqref{FreundEq} and \eqref{gasConc}, the contaminant mass concentraion in the soil and in equilibrium-sorbed sites $C_{soil,eq(t,i,k)}$ (mg pesticide per m$^{3}$ soil) is then:

$$ C_{soil,eq(t,i,k)} = \theta_{g(t,i,k)} C_{g(t,i,k)} + \theta_{(t,i,k)}C_{L(t,i,k)} + \rho_b X_{eq(t,i,k)} \stepcounter{equation}\tag{\theequation}\label{massEq}$$ 

Assuming $X_{ne,t=0}$ $\approx$ 0, non-equilibrium sorption is determined at each time step by a first-order rate equation:

$$ \frac{dX_{ne}}{dt}(i,k) = k_{des} \Big[K_{F,ne}\cdot C_{L,ref}\Big(\frac{C_{L(t,i,k)}}{C_{L,ref}}\Big)^{N}-X_{ne(t,i,k)}\Big] \stepcounter{equation}\tag{\theequation}\label{changeMassNe}$$  

where $t$ is time (d) and $k_{des}$ is the desorption rate coefficient (d$^{-1}$). Updating each time step is given by:

$$ X_{ne(t+1,i,k)} = X_{ne(t,i,k)} + \Delta X_{ne(t,i,k)} \stepcounter{equation}\tag{\theequation}\label{MassNe_t1}$$  


The non-equilibrium Freundlich coefficient (m$^{3}$ Kg$^{-1}$) is given by:

$$K_{F,ne} = f_{ne} \cdot K_{F,eq} \stepcounter{equation}\tag{\theequation}\label{KfNe}$$

Following Leistra $et~al.$ [-@Leistra2001], initial default values are $f_{ne}$ = 0.5 and $k_{des}$ = 0.01 d$^{-1}$. Values for $f_{ne}$ and $k_{des}$ should be derived from incubation experiments for a specific soil-contaminant combination and followed over a significant time period. Experimental results should determine concentration in the soil solution (i.e. by centrifugation) and bulk mass (i.e. by exhaustive extraction) of the contaminant. 

If the pesticide is mainly sorbed to the soil's organic matter $K_{F,eq}$ is then:

$$K_{F,eq} = f_{om} \cdot K_{om,eq} \stepcounter{equation}\tag{\theequation}\label{Kom}$$

were $f_{om}$ (kg kg$^{-1}$) is the fraction of organic matter in soil, $K_{om,eq}$ (m$^3$ Kg$^{-1}$) is the coeffficient of equilibrium sorption on soil organic matter and calculated from batch equilibration experiments of approximately 1 day. The fraction of organic matter can be related to the fraction of soil organic carbon according to [@Leistra2001]:

$$f_{oc} = 0.57 \cdot f_{om} \stepcounter{equation}\tag{\theequation}\label{omoc}$$

If sorption is affected differently by variation in soil constitutents (e.g. clay, iron and aluminum hydroxides) a more general definition of $K_{F,eq}$ may be necessary. In such cases a reference Freundlich coefficient $K_{F,eq,r}$ is used for the plough layer and a depth-dependent factor $f_{d,s}$ (-) is used to adjust sorption across depth horizons [@Leistra2001] such that:

$$K_{F,eq} = f_{d,s} \cdot K_{F,eq,r} \stepcounter{equation}\tag{\theequation}\label{Kom}$$

-------------

Doubt / current conundrum: 

How to adapt the sorption coefficient to differences in sorption to different soil constituents?

Leistra et al. [-@Leistra2001] state:

"The concept in which the coefficient for sorption on soil organic matter, $K_{om}$ , is used to calculate the coefficient $K_F$ for sorption on the whole soil does not hold for all pesticides. Soil constituents like clay minerals or iron and aluminium hydroxides may play a major role in the sorption of some (groups of) pesticides. For such cases, a more general provision is needed in the model. In anology to $K_{om}$ , a coefficient $K_{sc}$ for sorption on a soil constituent could be defined. The content of the soil constituent, $f_{sc}$ (kg kg$^{-1}$ ), is then specified as a function of depth in the soil. The coefficient $K_F$ for pesticide sorption on whole soil in the various horizons could then be calculated by:

$$K_{F,eq} = f_{sc} \cdot K_{sc} $$

In cases in which a pesticide is sorbed on two soil constituents, e.g. organic matter and clay, the user should specify the equivalent values of $K_{sc}$ and $f_{sc}$, using the information on the relative strength of sorption of the pesticide to the two soil constituents." (pp. 41-42)

-------------

### Biodegradation

Biodegradation in the soil is assumed to occur only on the dissolved and sorbed fraction on equilibrium sites. Assuming a first-order rate law:

$$ \frac{dM_{p(i,k)}}{dt} = -k_{b,L}(V_{L(t,i,k)}C_{L(t,i,k)})-k_{b,eq}(M_{s(i,k)}X_{eq(t,i,k)}) \stepcounter{equation}\tag{\theequation}\label{dMdt}$$

where liquid phase in the pore volume $V_L = A_i \cdot D_k\cdot \theta_{(t,i,k)}$ and $k_{b}$ (d$^{-1}$) is the biodegradation rate constant for the liquid ($L$) and equilibrium-sorbed sites ($eq$), respectively. 

Alternatively equation \eqref{dMdt} can subdivided and written in integrated form:

$$ M_{L(t+1,i,k)} = (V_{L(t,i,k)}C_{L(t,i,k)})e^{-k_{b} \Delta t} \stepcounter{equation}\tag{\theequation}\label{ML_t1}$$

$$ M_{eq(t+1,i,k)} = (M_{s(i,k)}X_{eq(t,i,k)})e^{-k_{b} \Delta t} \stepcounter{equation}\tag{\theequation}\label{Meq_t1}$$

where $M_{L}$ and $M_{eq}$ are the contamimant masses in liquid phase and equilibrium-sorbed sites, respectively.\footnote{A mass balance check should compute the equivalence of equation \eqref{dMdt} and $\Delta M_{L,eq}(t)$, equation \eqref{DeltaM}.} Updating for total contaminant mass using equations \eqref{MassNe_t1},  \eqref{ML_t1} and \eqref{Meq_t1}:

$$ M_{p(t+1,i,k)} = M_{L(t+1,i,k)} + M_{eq(t+1,i,k)} + M_{s(i,k)}X_{ne(t+1,i,k)} \stepcounter{equation}\tag{\theequation}\label{totmass_t1}$$

Before proceeding onto the following time step in the simulation, the mass in liquid phase from equation \eqref{ML_t1}, after mass transport processes, is used to compute a new iterative loop (i.e. equations \eqref{iterStep1} and \eqref{iterStep2}). Namely, 

$$ C_{L(i,k)} = \frac{M_{L(t+1,i,k)}}{A_i \cdot D_k \cdot \theta_{(t,i,k)}} \stepcounter{equation}\tag{\theequation}\label{C_Lnew}$$

The biodegradation rate constant $k_{b(L,eq)}$ is given by:

$$ k_b = \frac{ln(2)}{t_\frac{1}{2}} \stepcounter{equation}\tag{\theequation}\label{k_b}$$

where $t_\frac{1}{2}$ is the half-life (d) of the contaminant considered. Adapting the reference half-life to temperature and moisture changes following Dairon (cite: Dairon , 2015) the half-life becomes:

$$ t_\frac{1}{2}=t_\frac{1}{2}^{ref}\cdot F_T \cdot F_\theta \stepcounter{equation}\tag{\theequation}\label{DT50}	$$

where $t_\frac{1}{2}^{ref}$ is the half-life (days) at the reference moisture and temperature. $F_T$ and $F_\theta$ are factor changes in degradation rates associated to temperature and moisture conditions, respectively. To account for the influence of water content across a range of saturation conditions $F_\theta$ is given by (cite: Schroll et al, 2006):

$$
F_\theta = ...
$$
$$
F_T = ...
$$

where T is the temperature in soil layer k and time step t. $T_{ref}$ is the reference temperature at which the experimental half-life is reported (i.e. typically 20 $^{\circ}$C). $E_a$ is the activation energy generally equal to 54,000 (KJ mol$^{-1}$) and R is the gas constant 8.314 (J mol$^{-1}$ K$^{-1}$). 



#######






# References 
